services:
  db:
    image: postgres:16
    env_file:
      - ./.env.backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [internal]

  api:
    build:
      context: ./api
    env_file:
      - ./.env.backend
    depends_on:
      - db
    networks: [internal]

  web:
    build:
      context: ./web
    depends_on:
      - api
    networks: [internal]
    env_file:
      - ./.env.frontend
    environment:
      TURBORECS_API_URL: http://api:8080
    ports:
      - "3000:3000"

volumes:
  pgdata:

networks:
  internal:
    driver: bridge